#include "../include/codeGenerator.h"
#include <stdio.h>


void generateCode(Node* code, char* fileName) {
    FILE* file = fopen(fileName, "w");
    fprintf(file, "// Generated by codeGenerator\n");
}
