## Generated by codeGenerator
.data
.text
.global main

main:
addi sp, sp, -20
addi a4, sp, 4
addi a5, sp, 8
sw a5, 0(a4)
addi a6, sp, 12
sw a6, 4(a4)
li a5, 4
sw a5, -4(a4)
# start OP
li a0, 1
li a1, 0
li a2, 0
addi sp, sp, -4
sw a0, 0(sp)
addi sp, sp, -4
sw a1, 0(sp)
addi sp, sp, -4
sw a2, 0(sp)

# start OP
li a0, 0
li a1, 0
li a2, 0
addi sp, sp, -4
sw a0, 0(sp)
addi sp, sp, -4
sw a1, 0(sp)
addi sp, sp, -4
sw a2, 0(sp)

addi a4, sp, 28
mv a1, a4
lw a1, 0(a1)
lw a0, 0(a1)
lw a2, -4(a4)
lw a5, 0(sp)
addi sp, sp, 4
lw a4, 0(sp)
addi sp, sp, 4
lw a3, 0(sp)
addi sp, sp, 4

mul a6, a2, a3
add a1, a0, a6
lw a0, 0(a1)
# end OP
lw a5, 0(sp)
addi sp, sp, 4
lw a4, 0(sp)
addi sp, sp, 4
lw a3, 0(sp)
addi sp, sp, 4

sw a3, 0(a1)

# end OP
# start OP
li a0, 2
li a1, 0
li a2, 0
addi sp, sp, -4
sw a0, 0(sp)
addi sp, sp, -4
sw a1, 0(sp)
addi sp, sp, -4
sw a2, 0(sp)

# start OP
li a0, 1
li a1, 0
li a2, 0
addi sp, sp, -4
sw a0, 0(sp)
addi sp, sp, -4
sw a1, 0(sp)
addi sp, sp, -4
sw a2, 0(sp)

addi a4, sp, 28
mv a1, a4
lw a1, 0(a1)
lw a0, 0(a1)
lw a2, -4(a4)
lw a5, 0(sp)
addi sp, sp, 4
lw a4, 0(sp)
addi sp, sp, 4
lw a3, 0(sp)
addi sp, sp, 4

mul a6, a2, a3
add a1, a0, a6
lw a0, 0(a1)
# end OP
lw a5, 0(sp)
addi sp, sp, 4
lw a4, 0(sp)
addi sp, sp, 4
lw a3, 0(sp)
addi sp, sp, 4

sw a3, 0(a1)

# end OP
addi sp, sp, 20
## end function main

li a7, 10
ecall
